version: '3.5'

services:
  postgres:
    container_name: postgres_main_db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: warranties
    ports:
    - "5432:5432"
  warranties-app:
    image: warranties:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/warranties
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: secret
      IPGEOLOCATION_ENABLED: true #disable if you're planning to use a mock
      IPGEOLOCATION_API_KEY: <insert your own apikey here>
      IPGEOLOCATION_API_URL: https://api.ipgeolocation.io/ipgeo
    depends_on:
      - postgres