spring:
  application:
    name: warranties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        jdbc.lob.non_contextual_creation: true
        namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy

infra:
  geolocation:
    enabled: ${IPGEOLOCATION_ENABLED} # when geolocation is disabled by default it returns mocked value
    api:
      key: ${IPGEOLOCATION_API_KEY}
      url: ${IPGEOLOCATION_API_URL}